// Questionário 1 - Dons Ministeriais
const questoesDonsMinisteriais = [
    "1. Tenho capacidade de organizar, estabelecer e alcançar objetivos",
    "2. Tenho capacidade de motivar pessoas a trabalharem juntas",
    "3. Sinto-me bem em compartilhar o evangelho com pessoas que não conhecem a Cristo",
    "4. Tenho facilidade em identificar pessoas que estão precisando de ajuda",
    "5. Gosto de estudar e preparar material bíblico para ensinar outros",
    "6. Tenho facilidade em aconselhar pessoas que estão com problemas",
    "7. Gosto de trabalhar nos bastidores, ajudando outros a terem sucesso",
    "8. Tenho facilidade em delegar responsabilidades a outras pessoas",
    "9. Sinto-me realizado ao compartilhar minha fé com não cristãos",
    "10. Gosto de ajudar pessoas necessitadas, doentes ou solitárias",
    "11. Consigo comunicar a verdade bíblica de forma que as pessoas entendam",
    "12. Gosto de encorajar pessoas que estão desanimadas",
    "13. Gosto de servir outros para que o trabalho de Deus seja realizado",
    "14. Tenho facilidade em coordenar pessoas e projetos",
    "15. Tenho facilidade em me relacionar com não cristãos",
    "16. Sinto compaixão por pessoas que estão sofrendo",
    "17. Gosto de ajudar outros a entenderem a Bíblia",
    "18. Tenho facilidade em motivar outros em seu crescimento espiritual",
    "19. Gosto de atender às necessidades práticas de outras pessoas",
    "20. Tenho capacidade de estabelecer metas e planejar",
    "21. Tenho facilidade em convidar pessoas para aceitarem a Cristo",
    "22. Sinto-me bem em ajudar pessoas em necessidade",
    "23. Gosto de pesquisar e estudar para ensinar outros",
    "24. Tenho facilidade em incentivar outros a desenvolverem seus dons"
];

// Questionário 2 - Dons Espirituais
const questoesDonsEspirituais = [
    "1. Sinto-me chamado a iniciar novas igrejas",
    "2. Tenho facilidade em discernir a verdade do erro espiritual",
    "3. Tenho recebido revelações específicas de Deus para situações",
    "4. Tenho facilidade em comunicar o evangelho em outras culturas",
    "5. Tenho dom de curar pessoas através da oração",
    "6. Tenho facilidade em falar em línguas espirituais",
    "7. Deus tem me usado para realizar milagres",
    "8. Recebo orientação divina para situações específicas",
    "9. Tenho facilidade em interpretar línguas espirituais",
    "10. Sinto-me chamado a ministrar em outras culturas",
    "11. Pessoas têm sido curadas através do meu ministério",
    "12. Falo em línguas para edificação pessoal",
    "13. Deus tem operado sinais através do meu ministério",
    "14. Recebo direção divina para aconselhar outros",
    "15. Posso interpretar mensagens em línguas",
    "16. Tenho facilidade em me adaptar a outras culturas",
    "17. Oro com fé pela cura de enfermos",
    "18. Uso o dom de línguas em minhas orações",
    "19. Tenho visto Deus fazer o impossível",
    "20. Recebo palavras de sabedoria para situações",
    "21. Compreendo mensagens dadas em línguas",
    "22. Sinto-me chamado a evangelizar outros povos",
    "23. Pessoas são curadas quando oro por elas",
    "24. O Espírito Santo me dá palavras em outras línguas"
];

const donsMinisteriais = {
    "Liderança": [1, 2, 8, 14, 20],
    "Evangelismo": [3, 9, 15, 21],
    "Misericórdia": [4, 10, 16, 22],
    "Ensino": [5, 11, 17, 23],
    "Exortação": [6, 12, 18, 24],
    "Serviço": [7, 13, 19]
};

const donsEspirituais = {
    "Apostólico": [1],
    "Discernimento": [2],
    "Profecia": [3, 8, 14, 20],
    "Missões": [4, 10, 16, 22],
    "Cura": [5, 11, 17, 23],
    "Línguas": [6, 12, 18, 24],
    "Milagres": [7, 13, 19],
    "Interpretação": [9, 15, 21]
};

// Questionário de Dons Redentivos
const questoesRedentivas = [
    "1. Apresenta a verdade de maneira lógica e sistemática",
    "2. Guarda recursos financeiros para gerações futuras (ex.: filhos, netos, etc.)",
    "3. É altamente motivado para organizar e implementar planos",
    "4. É capaz de ter desentendimentos significativos sem ofender",
    "5. Tem uma tremenda capacidade de mostrar amor",
    "6. Identifica o certo rapidamente e com precisão",
    "7. Reconhece necessidades práticas e é rápido para atendê-las",
    "8. Valida a verdade confrontando-a com a realidade",
    "9. É capaz de aceitar pessoas com diversos pontos de vista",
    "10. Prefere estar sob autoridade para ter autoridade",
    "11. Evita ficar sozinho",
    "12. Sente a atmosfera emocional de um grupo/indivíduo",
    "13. Vê tudo como preto ou branco",
    "14. Gosta de mostrar hospitalidade",
    "15. Gosta de estudar e pesquisar",
    "16. Gosta de manter todas as opções abertas o maior tempo possível",
    "17. Suporta críticas para realizar a tarefa",
    "18. Relaciona-se com pessoas independentemente da cultura, raça, religião, origem, etc.",
    "19. Evita conflitos e confrontos",
    "20. Percebe facilmente o caráter de indivíduos ou grupos",
    "21. Permanece em algo até que esteja completo",
    "22. Enfatiza fatos e precisão das palavras",
    "23. Lida com todas as situações como uma situação única",
    "24. É hábil no gerenciamento do tempo",
    "25. Ama encorajar os outros a viverem vitoriosamente",
    "26. É atraído por pessoas sofrendo ou angustiadas",
    "27. Trabalha a partir de princípios",
    "28. Acha difícil dizer \"não\" aos pedidos de ajuda",
    "29. Resolve problemas começando com uma fundamentação teórica",
    "30. Tende a ser mais relativo do que absoluto",
    "31. Facilita recursos e pessoas para realizar tarefas ou alcançar objetivos",
    "32. Quer uma resposta visível ao ensinar ou falar",
    "33. Detecta facilmente falta de sinceridade ou motivações erradas",
    "34. Anseia por ver os seus próprios pontos cegos e ajudar os outros a verem os seus também",
    "35. Tem necessidade de ser apreciado",
    "36. Pega coisas emprestadas (ex.: livros) e não as devolve rapidamente",
    "37. Vê a família como importante",
    "38. Prefere seguir para um novo desafio quando algo é concluído",
    "39. É muito amado por causa da atitude positiva",
    "40. É cuidadoso com palavras e ações para evitar ferir os outros",
    "41. Sente necessidade de verbalizar ou dramatizar o que percebe",
    "42. Sente grande alegria em fazer algo que seja útil",
    "43. Tem fortes convicções e opiniões baseadas na investigação de fatos",
    "44. É preocupado com a comunidade",
    "45. Obtém sucesso sob estresse/pressão",
    "46. Vê provações como oportunidades para produzir crescimento pessoal",
    "47. É governado pelo coração e não pela cabeça",
    "48. Tem opiniões e convicções fortes",
    "49. Evita liderar outras pessoas ou projetos",
    "50. Gosta muito de escrever",
    "51. Vê dinheiro como segurança",
    "52. Quer ver as coisas concluídas o mais rápido possível",
    "53. Acha fácil se comunicar com os outros",
    "54. Percebe as coisas sem saber explicar \"como\"",
    "55. É franco, sincero e não mede palavras",
    "56. Apoia aqueles que estão na liderança",
    "57. Tende a usar ilustrações bíblicas em vez de ilustrações da vida",
    "58. Dá livremente bens/tempo/amor, mas sempre quer o melhor",
    "59. Gosta de projetos de longo prazo e não gosta de rotina",
    "60. Prefere aplicar a verdade em vez de pesquisá-la",
    "61. Alegra-se quando os outros são abençoados, se aflige quando são feridos",
    "62. Acredita que a tribulação produz quebrantamento/humildade",
    "63. Está mais interessado em satisfazer as necessidades dos outros do que nas próprias necessidades",
    "64. Fica chateado se as Escrituras são usadas fora do contexto",
    "65. Dá sem que outras pessoas saibam disso",
    "66. Pode facilmente delegar tarefas e supervisionar os outros",
    "67. Quer dar às pessoas instruções específicas sobre \"como fazer\"",
    "68. Não gosta de ser apressado",
    "69. Acredita que o verdadeiro arrependimento será evidenciado por bons frutos",
    "70. Trabalha com metas imediatas em vez de objetivos de longo prazo",
    "71. É autodisciplinado e autocontrolado",
    "72. Tem uma forte crença no dízimo/oferta de primícias",
    "73. Está disposto a deixar que os outros ganhem crédito para fazer o trabalho",
    "74. Gosta de fazer aconselhamento pessoal, mas para se não for visto nenhum esforço para mudar",
    "75. Tem dificuldade em dizer \"não\" aos outros",
    "76. Tende a ser dogmático",
    "77. Gosta de trabalhar sozinho",
    "78. Gosta de organizar informações/materiais",
    "79. Dá generosamente para projetos dignos",
    "80. Gosta de estabelecer e alcançar metas",
    "81. Tem facilidade em identificar com os que estão sofrendo",
    "82. Tem dificuldade em lidar com aqueles que são diferentes",
    "83. Tende a fazer julgamentos rápidos e firmes",
    "84. Prefere servir aos outros a ser servido",
    "85. Gosta de criar sistemas para organizar fatos",
    "86. Dá para suprir necessidades específicas",
    "87. É orientado para objetivos",
    "88. Gosta de encorajar o potencial em outros",
    "89. Tem profunda preocupação pelos outros",
    "90. Tende a ser crítico e julgar os outros",
    "91. Prefere apoiar a liderança a assumir a liderança"
];

// Mapeamento dos Dons Redentivos
const donsRedentivos = {
    "Mestre": [1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85],
    "Doador": [2, 9, 16, 23, 30, 37, 44, 51, 58, 65, 72, 79, 86],
    "Líder": [3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87],
    "Encorajador": [4, 11, 18, 25, 32, 39, 46, 53, 60, 67, 74, 81, 88],
    "Misericordioso": [5, 12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89],
    "Profeta": [6, 13, 20, 27, 34, 41, 48, 55, 62, 69, 76, 83, 90],
    "Servo": [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91]
};

// Sistema de pontuação
const pontuacao = {
    "NUNCA": 1,
    "ÀS VEZES": 2,
    "NA MAIORIA DAS VEZES": 3,
    "SEMPRE": 4
};

// Questionário de Dons Motivacionais
const questoesMotivacionais = [
    "1. Eu sou cuidadoso com o dinheiro e oro continuamente por sua distribuição adequada na obra do Senhor.",
    "2. Eu gosto de desenvolver maneiras de apresentar materiais que ajudem os outros a aprenderem mais facilmente.",
    "3. Facilmente delego tarefas para os outros.",
    "4. Eu me sinto feliz por ajudar alguém que está desanimado.",
    "5. Eu me encontro preocupado com os outros e seus problemas.",
    "6. Eu amo encorajar os outros a viverem vitoriosamente.",
    "7. Eu tenho experiência da interferência dos espíritos malignos em certas pessoas, lugares e coisas.",
    "8. Eu gosto de hospitalidade com uma oportunidade de doar.",
    "9. Eu gosto de explicar o que algo significa.",
    "10. Eu gosto mais de projetos de longo prazo (6 meses - 5 anos) do que projetos de curto prazo (1 dia - 2 semanas).",
    "11. Eu sou guiado pelo meu coração e não pela minha cabeça.",
    "12. Eu amo fazer aconselhamento pessoal.",
    "13. Eu amo fazer aconselhamento pessoal.",
    "14. Eu praticamente e com precisão identifico bem o mal e o bem.",
    "15. Eu sou capaz de administrar meus assuntos financeiros eficientemente para que eu possa doar generosamente para a obra do Senhor.",
    "16. Eu amo ver a luz do entendimento rompendo em outra pessoa.",
    "17. Eu sou capaz de estabelecer e fazer planos eficientes para alcançar metas.",
    "18. Eu prontamente simpatizo com as desgraças dos outros.",
    "19. Eu prefiro fazer as coisas sozinho do que educar.",
    "20. Eu geralmente tenho usando a experiência quando tento encontrar soluções para problemas.",
    "21. Eu sou profundamente com os pecados dos outros, assim como com os meus.",
    "22. Tenho o anseio de compartilhar o evangelho.",
    "23. Eu fico chateado quando as Escrituras são usadas fora de contexto.",
    "24. Eu penso que haja harmonia em uma organização para que ela funcione bem.",
    "25. Tenho uma grande preocupação com aqueles que estão passando por problemas.",
    "26. Eu gosto de tirar as cargas de pessoas-chave para que elas possam dar mais atenção às suas tarefas pessoais.",
    "27. Eu gosto de dar às pessoas instruções precisas para realizarem as ações.",
    "28. Eu vejo tudo como preto ou branco, certo ou errado, sem áreas cinzentas.",
    "29. A razão em primeiro lugar contrasta como o dinheiro que eu uso.",
    "30. Tenho prazer em me aprofundar em um livro da Bíblia para que eu possa passar para outras pessoas.",
    "31. Eu sou capaz de organizar ideias, pessoas, coisas e tempo para torná-los mais eficientes.",
    "32. Eu sou capaz de me relacionar com os outros emocionalmente e sou muito em ajudar quando necessário.",
    "33. Fico feliz em ajudar os outros sem necessariamente ser nomeado para uma posição de liderança.",
    "34. Eu aceito as pessoas como elas são, sem julgá-las.",
    "35. Anseio por ver meus próprios pontos cegos e ajudar os outros a verem os seus também.",
    "36. Eu só dou quando guiado pelo Espírito Santo, verificando com Ele o quanto eu devo doar.",
    "37. Tenho prazer em largas pesquisas para estabelecer o ensino e a doutrina correta.",
    "38. Eu sou capaz de me ater aos detalhes e garantir que os planos que foram feitos sejam realizados.",
    "39. Detecto facilmente falta de sinceridade ou motivações erradas.",
    "40. Eu gosto mais de projetos de curto prazo (1 dia - 2 semanas) do que de longo prazo (6 meses - 5 anos).",
    "41. Eu tomo decisões com rapidez e facilidade.",
    "42. Eu sou frequentemente franco, direto e não meço palavras.",
    "43. Eu gosto de compartilhar o tempo que tenho com os outros para a extensão do Reino de Deus.",
    "44. Preocupa-me que a verdade seja apresentada de maneira clara, com atenção adequada ao significado e exatidão das palavras.",
    "45. Eu gosto de supervisionar o trabalho que precisa ser feito.",
    "46. Tenho/cultivo o confronto.",
    "47. Eu gosto quando os outros expressam a necessidade da minha ajuda.",
    "48. Tenho uma profunda preocupação em incentivar as pessoas para o crescimento espiritual.",
    "49. Eu sou consciente de ser persuasivo quando falo com as pessoas.",
    "50. Sinto-me profundamente comovido quando confrontado com necessidades financeiras urgentes na obra de Deus.",
    "51. Eu sou capaz de explicar bem como tais e tais Bíblia se encaixa.",
    "52. Sou profundamente sensível à necessidade de uma boa administração, de modo que todas as fases da atividade sejam executadas com decência e ordem.",
    "53. Eu gosto de atrair pessoas com necessidades e problemas.",
    "54. Eu tenho muito tempo para ignorar meus próprios confortos pessoais para que as necessidades de outros sejam atendidas.",
    "55. Eu sou capaz de encorajar espiritualmente aqueles que hesitam e estão espiritualmente perturbados.",
    "56. Eu sou chamado para a intercessão.",
    "57. Costumo mimar meus filhos e outros parentes próximos.",
    "58. Eu gosto de estudar a Palavra.",
    "59. Eu sou naturalmente orientado pelos meus objetivos.",
    "60. Eu sou comumente cercado pelos meus pensamentos.",
    "61. Eu tenho uma forte crença de que tudo que eu possuo pertence a Deus.",
    "62. Sempre concluo o que começo.",
    "63. Eu acredito e espero que produz bons frutos.",
    "64. Eu tenho bem sucedido em ganhar riqueza pessoal.",
    "65. Sou facilmente adaptável a novos interesses.",
    "66. Eu faria gosto de tarefas rotineiras.",
    "67. Sou alegre e bem disposto em todas as circunstâncias.",
    "68. Eu tenho a habilidade de fazer as pessoas se sentirem em casa.",
    "69. Muitas vezes perco de mim - causa de responsabilidade para refletir ideias e pensamentos.",
    "70. Muitas vezes posso discernir o espírito e a atitude de uma pessoa.",
    "71. Não gosto de pedir dinheiro.",
    "72. Costumo verificar a fonte do conhecimento daqueles que me ensinam.",
    "73. Estou disposto a deixar que os outros recebam o crédito por fazer o trabalho.",
    "74. Não gosto de ser agressivo em um trabalho ou situação.",
    "75. Eu costumo ser perfeccionista.",
    "76. Eu espero muito de mim mesmo e dos outros.",
    "77. Eu desejo ser obediente a Deus - não importa o custo.",
    "78. Não tenho nenhum problema em confiar com alegria meus bens a outros para o trabalho do ministério.",
    "79. Sou objetivo que naturalmente.",
    "80. Eu prefiro manter minhas decisões até que algo seja concluído.",
    "81. Costumo fazer orações pelos outros.",
    "82. Eu tenho necessidade de me sentir apreciado.",
    "83. Eu gosto de esclarecer os problemas com os outros rapidamente.",
    "84. Eu tenho dificuldade com pessoas estritas.",
    "85. Tenho preocupação com a questão da assistência financeira disponível para todas as áreas da obra de Deus.",
    "86. Sou emocionalmente autocontrolado.",
    "87. Eu gosto de ver uma tarefa concluída o mais rápido possível.",
    "88. Eu tenho dificuldade em dizer \"não\" quando me pedem ajuda.",
    "89. Eu tenho dificuldade em dizer \"não\" aos pedidos de ajuda.",
    "90. Eu sou muito querido por causa da minha atitude positiva.",
    "91. Tenho opiniões e convicções fortes.",
    "92. Eu dou gosto dos dons: tempo, pessoas, amor e dinheiro ao trabalho do Senhor.",
    "93. Eu resolvo problemas a partir de princípios das Escrituras.",
    "94. Eu gosto de trabalhar com pessoas e de ver que elas se deem bem.",
    "95. Sou motivado para ajudar as pessoas a terem relacionamentos corretos umas com as outras.",
    "96. Eu mantenho tudo meticulosamente em ordem.",
    "97. Se eu estiver aconselhando alguém e não ver nenhum esforço da pessoa para mudar, paro.",
    "98. Eu costumo ser introspectivo.",
    "99. Dou mais de 10% da minha renda.",
    "100. Sinto que o estudo da Bíblia é fundamental para a operação de todos os dons.",
    "101. Eu não tenho nenhum problema em estar sob autoridade para exercer autoridade.",
    "102. Eu tomo medidas para aliviar a aflição e remover mágoas dos outros.",
    "103. Eu gosto de projetos e trabalhos manuais.",
    "104. Sou fluente em comunicação.",
    "105. Eu acredito que a Bíblia é a base para a verdade, a confiança, a ação e a autoridade.",
    "106. Eu amo doar sem que os outros saibam sobre isso.",
    "107. Tenho fortes convicções e opiniões baseadas na investigação de fatos.",
    "108. Normalmente não assumo responsabilidades, a menos que sejam delegadas a mim por aqueles que estão em posição de autoridade.",
    "109. Eu posso perceber a atmosfera espiritual emocional de um grupo ou pessoa.",
    "110. Eu sou uma pessoa trabalhista e tenho uma boa memória.",
    "111. Eu me concentro em trabalhar com pessoas.",
    "112. Sou guiado quando sigo em princípios espirituais.",
    "113. Eu intercedo pelas necessidades das pessoas pela salvação das almas.",
    "114. É importante que a verdade seja estabelecida em todas as situações.",
    "115. Assumirei a responsabilidade se não houver uma liderança específica.",
    "116. Eu tenho a tendência de ser inclusivo.",
    "117. Eu mostro mais amor em ações e atitudes do que em palavras.",
    "118. Eu gosto de ter uma resposta visível ao falar com as pessoas.",
    "119. Eu faço tudo que posso para promover o crescimento espiritual das pessoas.",
    "120. Eu não sou ingênuo.",
    "121. Eu sou perspicaz.",
    "122. Eu sofro críticas a fim de fazer o melhor.",
    "123. Sou facilmente ferido pelos outros.",
    "124. Costumo criticar pessoas que não ajudam com necessidades.",
    "125. Uso as Escrituras fora do contexto para apresentar um ponto.",
    "126. Eu costumo ser muito controlador.",
    "127. Eu tenho uma habilidade natural e eficaz para negócios.",
    "128. Eu acredito que tudo tem o poder intrínseco de organizar padrões.",
    "129. Tenho que tomar cuidado para não usar as pessoas para fazer o trabalho.",
    "130. Minha natureza afetuosa é muitas vezes mal interpretada pelo sexo oposto.",
    "131. Acho difícil aceitar ser servido por outros.",
    "132. Eu sou sensível a opiniões fortes.",
    "133. Eu posso ser intolerante com opiniões e pontos de vista diferentes dos meus.",
    "134. Eu tendo a preferir trabalhar com o que já há necessidade.",
    "135. Eu não aceito os pontos de vista dos outros muito rapidamente.",
    "136. Eu tenho tendência a julgar a mim mesmo negligente minhas necessidades pessoais e familiares.",
    "137. Tenho propensão a tomar para mim a ofensa feita a outra pessoa.",
    "138. Eu me mostro facilmente quando sou menosprezado.",
    "139. Eu posso ser muito crítico.",
    "140. Eu luto com problemas de autoestima."
];

// Mapeamento dos Dons Motivacionais
const donsMotivacionais = {
    "Doador": [1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106, 113, 120, 127, 134],
    "Mestre": [2, 9, 16, 23, 30, 37, 44, 51, 58, 65, 72, 79, 86, 93, 100, 107, 114, 121, 128, 135],
    "Líder": [3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94, 101, 108, 115, 122, 129, 136],
    "Misericordioso": [4, 11, 18, 25, 32, 39, 46, 53, 60, 67, 74, 81, 88, 95, 102, 109, 116, 123, 130, 137],
    "Servo": [5, 12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89, 96, 103, 110, 117, 124, 131, 138],
    "Encorajador": [6, 13, 20, 27, 34, 41, 48, 55, 62, 69, 76, 83, 90, 97, 104, 111, 118, 125, 132, 139],
    "Profeta": [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140]
};

// Sistema de pontuação dos Dons Motivacionais
const pontuacaoMotivacional = {
    "NUNCA": 0,
    "RARAMENTE": 1,
    "ÀS VEZES": 2,
    "USUALMENTE": 3,
    "NA MAIORIA DAS VEZES": 4,
    "SEMPRE": 5
};

// Sistema de pontuação para cada tipo de questionário
const sistemaPontuacao = {
    ministerial: {
        "NUNCA": 0,
        "RARAMENTE": 1,
        "OCASIONALMENTE": 2,
        "FREQUENTEMENTE": 3,
        "MUITO FREQUENTEMENTE": 4,
        "SEMPRE": 5
    },
    redentivo: {
        "NUNCA": 1,
        "ÀS VEZES": 2,
        "NA MAIORIA DAS VEZES": 3,
        "SEMPRE": 4
    },
    motivacional: {
        "NUNCA": 1,
        "RARAMENTE": 2,
        "OCASIONALMENTE": 3,
        "FREQUENTEMENTE": 4,
        "SEMPRE": 5
    }
};